repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: check-added-large-files

- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: system
    types: [python]
    require_serial: true