version: "1"
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "9050:80"
      # The Web UI (enabled by --api.insecure=true)
      - "9051:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  #Queue Node
  manager:
    image: rhnode/manager:latest
    build: 
      context: ../
      dockerfile: nodes/queue/Dockerfile

    expose:
    - "8000"

    labels:
      - "traefik.http.routers.manager.rule=PathPrefix(`/manager`) || Path(`/`)"

    environment:
      RH_OTHER_ADDRESSES: "peyo:9050"
      RH_NAME: "tower"
      RH_MEMORY: 32
      RH_GPU_MEM: "9"
      RH_PROCESSES: 64

  ## Test node
  testnode:
    image: rhnode/testnode:latest

    build: 
      context: ../
      dockerfile: nodes/testnode/Dockerfile

    expose:
      - "8000"
    labels:
      - "traefik.http.routers.testnode.rule=PathPrefix(`/testnode`)"


  #HD BET Node
  hdbet:
    image: rhnode/hdbet:latest

    build: 
      context: ../
      dockerfile: nodes/hdbet/Dockerfile

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    expose:
      - "8000"
      
    labels:
      - "traefik.http.routers.hdbet.rule=PathPrefix(`/hdbet`)"
    
  #Zerodose Node
  zerodose:
    image: rhnode/zerodose:latest

    build: 
      context: ../
      dockerfile: nodes/zerodose/Dockerfile
    expose:
      - "8000"
    labels:
      - "traefik.http.routers.zerodose.rule=PathPrefix(`/zerodose`)"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              
  addnode:
    image: rhnode/addnode:latest
    build: 
      context: ../
      dockerfile: nodes/addnode/Dockerfile
    expose:
      - "8000"
    labels:
      - "traefik.http.routers.addnode.rule=PathPrefix(`/add`)"
  
