
version: "1" #Arbitrary
services:

  add: #Same name as node.name
    image: rhnode/add:latest
    build: .
    ports:
      - "8010:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
